name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release-binaries:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libdbus-glib-1-dev
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kv_downloader
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
